name = "PipeChannels"
uuid = "316ea068-b8d4-4418-b34f-158552ec34f5"
version = "0.1.2"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@outlook.com>"]

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
